exports.myPage = function(lista, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h2>Task List</h2>
                </header>
            
                <form class="w3-container w3-mobile" method="POST">
                    <fieldset class="w3-margin">
                        <legend>Add task</legend>
                        <label>Description:</label>
                        <input class="w3-input w3-round" type="text" name="description" required>
                        <label>Author:</label>
                        <input class="w3-input w3-round" type="text" name="author" required>
                        <label>Date:</label>
                        <input class="w3-input w3-round" type="date" name="dateDued" required>
                        <input type="hidden" name="id" value="${lista.length+1}">
                    </fieldset>
                    <button class="w3-btn w3-blue w3-mb-2 w3-margin" type="submit">Add new Task</button>
                </form>
                <!-- tables side by side -->
                <div class="w3-row-padding w3-mobile">
                    <div class="w3-half">
                        <h2>To Do</h2>
                        <table class="w3-table w3-bordered w3-striped w3-border w3-hoverable w3-white">
                            <thead>
                                <tr class="w3-blue">
                                    <th>Description</th>
                                    <th>Author</th>
                                    <th>Due Date</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>`

    for(let i = 0; i < lista.length; i++){
        if(lista[i].done == false) {
            console.log("lista[i]",lista[i])
            pagHTML += `
                                <!-- each row has a form to submit to mark it as done-->
                                <tr>
                                    <td>${lista[i].description}</td>
                                    <td>${lista[i].author}</td>
                                    <td>${lista[i].dateDued}</td>
                                    <td>
                                        <form method="POST">
                                            
                                            <input type="hidden" name="description" value="${lista[i].description}">
                                            <input type="hidden" name="author" value="${lista[i].author}">
                                            <input type="hidden" name="dateDued" value="${lista[i].dateDued}">
                                            <input type="hidden" name="id" value="${lista[i].id}">
                                            <input type="hidden" name="done" value="${lista[i].done}">
                                            <button class="w3-btn w3-blue w3-mb-2 w3-margin" type="submit">Mark as Done</button>
                                        </form>
                                    </td>
                                </tr>`
        }
        
    }

    pagHTML += `
                            </tbody>
                        </table>
                    </div>
                    <div class="w3-half">
                        <h2>Resolved</h2>
                        <table class="w3-table w3-bordered w3-striped w3-border w3-hoverable w3-white">
                            <thead>
                                <tr class="w3-blue">
                                    <th>Description</th>
                                    <th>Author</th>
                                    <th>Due Date</th>  
                                </tr>
                            </thead>
                            <tbody>`


    for(let i = 0; i < lista.length; i++){
        if(lista[i].done == true) {
            pagHTML += `
                                <tr>
                                    <td>${lista[i].description}</td>
                                    <td>${lista[i].author}</td>
                                    <td>${lista[i].dateDued}</td>
                                </tr>`

        }
        
    }

    pagHTML += `
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- <footer class="w3-container w3-blue">
                    <h5>Generated by RPCW2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer> -->
            
            </div>
            `
    return pagHTML
}